version: "3.8"
services:
  app:
    container_name: "app"
    env_file:
      - ./app/.env
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        EXPOSED_PORT: ${LISTENING_PORT}
    volumes:
      - ./app/:/app/
      - "/app/node_modules"
    command: ash -c "npm install && npm run start"
    ports:
      - ${LISTENING_PORT}:${LISTENING_PORT}
