version: "3.8"
services:
  app:
    container_name: "app"
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        EXPOSED_PORT: ${LISTENING_PORT}
    volumes:
      - ./app/:/app/
      - "/app/node_modules"
    command: ash -c "npm install && npm run start:dev"
    ports:
      - ${LISTENING_PORT}:${LISTENING_PORT}
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
    postgres_data: